### ISSUE TITLE
Finish github

### ISSUE THREAD

**Issue by Leohemmingsson** [Leohemmingsson/D0018E#1]
# Task description
This task is to set up the whole project and the base for how it will look.

# When is the issue done
The issue is done when TODO is completed.

# How is it tested
The tests will only be manual tests, where the assignee will try the environment and test the ignore files.

# TODO
* [x] Add files and configs for working flow
* [x] Create the venv/docker files
* [x] Add git ignore
