### ISSUE TITLE
Create frontpage

### ISSUE THREAD

**Issue by Leohemmingsson** [Leohemmingsson/D0018E#10]
## Task description
Create a front page that displays all the products as a grid, the product information comes from DB. The page should also have a navbar. The navbar should include a search bar, login button, etc.

## When is the issue done
When the front page can display all products, and looks okay.

## How is it tested
There are only manual tests, making sure links, etc work as expected.

## TODO
* [x] Create the main HTML file
* [x] Link to CSS
* [x] Create a navbar
* [ ] Add filter functionality (?) might do this in a later step
