### ISSUE TITLE
Create shopping basket

### ISSUE THREAD

**Issue by Leohemmingsson** [Leohemmingsson/D0018E#11]
## Task description
This is the page to display the items in the shopping cart. It should be at path "/cart" and get the shopping cart for the logged-in user through the DB

## When is the issue done
When a logged-in user can add items to the cart and see them on the cart page

## How is it tested
Manually

## TODO
* [ ] Create the sidebar which is our basket for some reason :)
* [ ] Render through the list from DB and display all the items
* [ ] Try removing items (maybe changing quantity from the cart)
* [ ] Test
