### ISSUE TITLE
Create admin item view

### ISSUE THREAD

**Issue by Leohemmingsson** [Leohemmingsson/D0018E#12]
## Task description
Make an admin page, from here you should be able to add/remove/edit items.

### Features:
* Change quantity
* Remove item
* Add new items
* Change description
* Change tags on items

## When is the issue done
When all the features in the list above are added.

## How is it tested
Manually

## TODO
* [x] Add an item overview (render over DB return and display all items)
* [x] Function for adding items
* [x] Function for removing items
* [x] Editing info on items
