### ISSUE TITLE
Create admin user view

### ISSUE THREAD

**Issue by Leohemmingsson** [Leohemmingsson/D0018E#15]
## Task description
Make an admin page, from here you should be able to add/remove/edit users.

## When is the issue done
All featured below are added: 
* Change user to admin
* Remove users (only if a user is not admin)
* Add new users

## How is it tested
Manually

## TODO
* [x] Add a user overview (render over DB return and display all users)
* [x] Function to add a user
* [x] Function to remove user
* [x] Edit user permission
