### ISSUE TITLE
Make login-page pretty

### ISSUE THREAD

**Issue by Leohemmingsson** [Leohemmingsson/D0018E#18]
## Task description
Make the login page look like it belongs, so the same structure as the homepage. So the same navbar without buttons (maybe home) and maybe put the login boxes in the middle. All other "make it pretty" suggestions are welcome

## When is the issue done
The login page looks at least okay, it should not look misplaced.

## How is it tested
Just make sure nothing is destroyed

## TODO
* [x] Add navbar - without buttons just the color ish
* [x] Add put login in the middle
* [x] Other alternative features
