### ISSUE TITLE
Setup server

### ISSUE THREAD

**Issue by Leohemmingsson** [Leohemmingsson/D0018E#3]
# Task description
Set up RPI to run the web server, fixing access from the router.

# When is the issue done
When anyone can access the mock-up webpage.

# How is it tested
Try accessing through ssh, test to run the 

# TODO
* [x] Set up user accounts
* [x] Port configs on the router
* [x] Set up SSH access.
* [x] Install requirements such as docker or python venvs etc,
