### ISSUE TITLE
DB abstraction

### ISSUE THREAD

**Issue by Leohemmingsson** [Leohemmingsson/D0018E#33]
## Task description
Create different SQL commands.

## When is the issue done
When all current issues can be solved (SQL part)

## How is it tested
Manually, try the added functions

## TODO
* [x] Add stuff for the basket
* [x] Add for admin item view
* [x] Add for sign-up
