### ISSUE TITLE
Creating database

### ISSUE THREAD

**Issue by Leohemmingsson** [Leohemmingsson/D0018E#4]
# Task description
Here we should create a database on the server, and also write the script to set up the database. This is done by following the UML diagram written.

# When is the issue done
When the database is accessible.

# How is it tested
Try inserting new instances and making sure the relationships work as expected.  This could be done manually or by code.

# TODO
* [x] Set up a database on the raspberry pi
* [x] Write script for database
* [x] Start the testing
