### ISSUE TITLE
Fix admin first page

### ISSUE THREAD

**Issue by Leohemmingsson** [Leohemmingsson/D0018E#46]
## Task description
When logging in as an admin the user should be able to choose which view to see. So an admin should get a menu page for either user or item view. Further, we need a way to navigate back to the admin menu. This could be done with a dynamic navbar that changes depending on whether you are a customer or an admin.

## When is the issue done
When it looks ish ok, it is possible to navigate through the admin pages.

## How is it tested
Manually, making sure nothing is broken. 

## TODO
* [ ] Add admin first page
* [ ] Add dynamic navbar
* [ ] Make sure nothing else is broken

**Comment by Kallzor** [comment]
"This could be done with a dynamic navbar that changes depending on whether you are a customer or an admin" 

Mellanchef's förslag på en lösning smh
