### ISSUE TITLE
Reviews - Hook up reviews to DB

### ISSUE THREAD

**Issue by Leohemmingsson** [Leohemmingsson/D0018E#47]
## Task description
Connect reviews to DB, so reviews are shown. Also, make it possible to add reviews.

## When is the issue done
When reviews are displayed and it is possible to add a review.

## How is it tested
Manually, making sure reviews works.

## TODO
* [ ] Add review iterations
* [ ] Add so reviews can be added
* [ ] Add product review stars depending on reviews
