### ISSUE TITLE
UML-structure

### ISSUE THREAD

**Issue by Kallzor** [Leohemmingsson/D0018E#5]
# Task description
 Finish creating the UML diagram that is supposed to represent our SQL database. 

# When is the issue done
When the lab supervisor has given us an OK. 

# How is it tested
Could you double-check with the lab supervisor if the structure is fine?

# TODO
* [x] Plan ahead of how the structure of our project would look like and how we want things to be related to each other. 
* [x] Create a UML diagram
* [x] Check with the lab supervisor
