### ISSUE TITLE
Add admin_review and admin_tag view for admins

### ISSUE THREAD

**Issue by Kallzor** [Leohemmingsson/D0018E#50]
## Task description
When you're an admin you'd want to edit/remove/add tags and reviews (maybe not add reviews because that's sus).
Make 2 different pages for that connect with admin index page and the navbar. 

## When is the issue done
When it looks ish ok, it is possible to navigate through the admin pages.

## How is it tested
Manually, making sure nothing is broken. 

## TODO
* [x] Add admin review/tag page
* [x] Fix navbar
* [ ] Make sure nothing else is broken
* [ ] JS for each added page
