### ISSUE TITLE
implement database usage in webserver

### ISSUE THREAD

**Issue by Epos95** [Leohemmingsson/D0018E#6]
# Task description
Make the webserver use the database for its queries and data.

# When is the issue done
When the database is in use inside the webserver without any issues.

# How is it tested
CRUD works through the webserver to the database.

# TODO
* [ ] Create remote connection to database in webserver
* [ ] Read from the database
* [ ] Present data from DB through the webserver
* [ ] Insert data via the webserver to the DB
