### ISSUE TITLE
implement logins

### ISSUE THREAD

**Issue by Epos95** [Leohemmingsson/D0018E#9]
## Task description
Create a login/user system so that certain pages can only be viewed by certain users and some actions require a user to be logged in.

## When is the issue done
The issue is done when login works, and login is stored in cookies.

## How is it tested
The user can login and certain pages should be blocked off from unauthorized users

## TODO
* [x] Create the HTML page for login
* [x] Connect to the database
* [x] Verify that added user credential works.
* [ ] Add login delay (?) to prevent brute force attacks
